module.exports = {
    LOGIN_START: 'LOGIN_START_!',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS_!',
    LOGIN_FAILURE: 'LOGIN_FAILURE_!',

    LOGOUT_START: 'LOGOUT_START',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGOUT_FAILURE: 'LOGOUT_FAILURE',
};
